"use strict";
const express=require("express");
const cors=require("cors");
const {Pool}=require("pg");
const app=express();
app.use(cors());
app.use(express.json({limit:"100kb"}));
const PORT=Number(process.env.PORT||10000);
const DATABASE_URL=process.env.DATABASE_URL;
const PI_API_KEY=process.env.PI_API_KEY;
const TESTNET_MODE=String(process.env.TESTNET_MODE||"true").toLowerCase()==="true";
const DEVELOPER_USERNAME=String(process.env.DEVELOPER_USERNAME||"utoy0913").replace(/^@/,"").trim();
const PI_PLATFORM_API="https://api.minepi.com/v2";
const MINING_RATE=.25,MINING_HOURS=24,DAILY_LIMIT=6;
const TEST_PRODUCT_ID="adt-developer-test-pet",TEST_PRODUCT_PRICE=.1;
const pool=DATABASE_URL?new Pool({connectionString:DATABASE_URL,ssl:{rejectUnauthorized:false}}):null;
async function query(text,params=[]){if(!pool)throw new Error("DATABASE_URL is not configured.");return pool.query(text,params)}
async function piApiRequest(path,method="GET",body=null){if(!PI_API_KEY)throw new Error("PI_API_KEY is not configured.");const o={method,headers:{Authorization:`Key ${PI_API_KEY}`,"Content-Type":"application/json"}};if(body!==null)o.body=JSON.stringify(body);const r=await fetch(PI_PLATFORM_API+path,o),t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{d={raw:t}}if(!r.ok){const e=new Error(d.error_message||d.error||`Pi API request failed (${r.status}).`);e.status=r.status;throw e}return d}
async function verifyPiAccessToken(token){if(typeof token!=="string"||token.length<10){const e=new Error("Pi access token is required.");e.status=401;throw e}const r=await fetch(`${PI_PLATFORM_API}/me`,{headers:{Authorization:`Bearer ${token}`}}),t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{}if(!r.ok||!d||typeof d.username!=="string"){const e=new Error("Pi authentication could not be verified.");e.status=401;throw e}return d}
function bearer(req){const h=req.headers.authorization||"";return h.startsWith("Bearer ")?h.slice(7).trim():null}
async function requirePiUser(req){const u=await verifyPiAccessToken(bearer(req));const requested=typeof req.body?.piUsername==="string"?req.body.piUsername:typeof req.query?.piUsername==="string"?req.query.piUsername:null;if(requested&&requested!==u.username){const e=new Error("Pi account does not match the requested username.");e.status=403;throw e}return u}
function authError(res,e){return res.status(e.status||500).json({error:e.message||"Authentication failed."})}
async function initializeDatabase(){await query(`
CREATE TABLE IF NOT EXISTS users(id BIGSERIAL PRIMARY KEY,pi_username TEXT UNIQUE NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS balances(user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,available_adt NUMERIC(30,8) NOT NULL DEFAULT 0,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS mining_sessions(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),stopped_at TIMESTAMPTZ,status TEXT NOT NULL DEFAULT 'active',rate_adt_per_hour NUMERIC(20,8) NOT NULL,earned_adt NUMERIC(30,8) NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS payments(id BIGSERIAL PRIMARY KEY,payment_id TEXT UNIQUE NOT NULL,pi_username TEXT,product TEXT,amount NUMERIC(20,8),txid TEXT UNIQUE,status TEXT NOT NULL DEFAULT 'created',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),completed_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS purchases(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,payment_id TEXT UNIQUE NOT NULL,product TEXT NOT NULL,amount NUMERIC(20,8) NOT NULL,txid TEXT UNIQUE NOT NULL,purchased_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS wallet_profiles(user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,wallet_address TEXT,verification_status TEXT NOT NULL DEFAULT 'unverified',verification_method TEXT,verified_at TIMESTAMPTZ,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS reputation_profiles(user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,score INTEGER NOT NULL DEFAULT 0,level TEXT NOT NULL DEFAULT 'New Miner',completed_mining_cycles INTEGER NOT NULL DEFAULT 0,wallet_verified BOOLEAN NOT NULL DEFAULT FALSE,marketplace_purchases INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS marketplace_products(id BIGSERIAL PRIMARY KEY,product_id TEXT UNIQUE NOT NULL,name TEXT NOT NULL,price NUMERIC(20,8) NOT NULL,currency TEXT NOT NULL DEFAULT 'Pi',visibility TEXT NOT NULL DEFAULT 'public',active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
INSERT INTO marketplace_products(product_id,name,price,currency,visibility,active) VALUES('${TEST_PRODUCT_ID}','ADT Digital Pet - Developer Test',.1,'Test-Pi','developer',TRUE) ON CONFLICT(product_id) DO UPDATE SET name=EXCLUDED.name,price=EXCLUDED.price,currency=EXCLUDED.currency,visibility=EXCLUDED.visibility,active=EXCLUDED.active);`)}
async function getUser(name){const r=await query(`SELECT id,pi_username FROM users WHERE pi_username=$1`,[name]);return r.rows[0]||null}
async function profiles(id){await query(`INSERT INTO balances(user_id) VALUES($1) ON CONFLICT(user_id) DO NOTHING`,[id]);await query(`INSERT INTO wallet_profiles(user_id) VALUES($1) ON CONFLICT(user_id) DO NOTHING`,[id]);await query(`INSERT INTO reputation_profiles(user_id) VALUES($1) ON CONFLICT(user_id) DO NOTHING`,[id])}
function level(s){if(s>=900)return"Legend Miner";if(s>=700)return"Elite Miner";if(s>=500)return"Trusted Miner";if(s>=300)return"Established Miner";if(s>=100)return"Active Miner";return"New Miner"}
async function reputation(id){const r=await query(`SELECT rp.completed_mining_cycles,rp.marketplace_purchases,wp.verification_status FROM reputation_profiles rp JOIN wallet_profiles wp ON wp.user_id=rp.user_id WHERE rp.user_id=$1`,[id]);if(!r.rows.length)return null;const x=r.rows[0],score=Math.min(1000,Number(x.completed_mining_cycles||0)*10+(x.verification_status==="verified"?100:0)+Number(x.marketplace_purchases||0)*20),lv=level(score);await query(`UPDATE reputation_profiles SET score=$1,level=$2,wallet_verified=$3,updated_at=NOW() WHERE user_id=$4`,[score,lv,x.verification_status==="verified",id]);return{score,level:lv}}
app.get("/",(q,s)=>s.json({service:"Alberto Digital Token",status:"online",version:"2.1.0",environment:TESTNET_MODE?"TESTNET":"MAINNET"}));
app.get("/health",async(q,s)=>{try{if(pool)await query("SELECT 1");s.json({ok:true,database:Boolean(pool),piApiKeyConfigured:Boolean(PI_API_KEY),testnetMode:TESTNET_MODE,time:new Date().toISOString()})}catch(e){s.status(503).json({ok:false,database:false})}});
app.post("/api/users",async(q,s)=>{try{const u=await requirePiUser(q);const r=await query(`INSERT INTO users(pi_username) VALUES($1) ON CONFLICT(pi_username) DO UPDATE SET pi_username=EXCLUDED.pi_username RETURNING id,pi_username,created_at`,[u.username]);await profiles(r.rows[0].id);s.status(201).json({user:r.rows[0]})}catch(e){authError(s,e)}});
app.post("/api/mining/start",async(q,s)=>{try{const u=await requirePiUser(q),user=await getUser(u.username);if(!user)return s.status(404).json({error:"User not found. Please sign in again."});await profiles(user.id);const a=await query(`SELECT id,started_at FROM mining_sessions WHERE user_id=$1 AND status='active' ORDER BY started_at DESC LIMIT 1`,[user.id]);if(a.rows.length){const row=a.rows[0],start=new Date(row.started_at),end=new Date(start.getTime()+MINING_HOURS*3600000);return s.status(409).json({error:"Mining is already active.",active:true,sessionId:row.id,startedAt:start.toISOString(),endsAt:end.toISOString(),miningRate:MINING_RATE,miningHours:MINING_HOURS,maximumEarnedADT:DAILY_LIMIT})}const r=await query(`INSERT INTO mining_sessions(user_id,rate_adt_per_hour,status) VALUES($1,$2,'active') RETURNING id,started_at`,[user.id,MINING_RATE]);const row=r.rows[0],start=new Date(row.started_at),end=new Date(start.getTime()+MINING_HOURS*3600000);s.status(201).json({message:"ADT mining started.",sessionId:row.id,startedAt:start.toISOString(),endsAt:end.toISOString(),miningRate:MINING_RATE,miningHours:MINING_HOURS,maximumEarnedADT:DAILY_LIMIT})}catch(e){authError(s,e)}});
app.get("/api/mining/status",async(q,s)=>{try{const u=await requirePiUser(q),r=await query(`SELECT ms.id,ms.started_at,ms.rate_adt_per_hour FROM mining_sessions ms JOIN users u ON u.id=ms.user_id WHERE u.pi_username=$1 AND ms.status='active' ORDER BY ms.started_at DESC LIMIT 1`,[u.username]);if(!r.rows.length)return s.json({active:false,canClaim:false,earnedADT:0,remainingSeconds:0});const x=r.rows[0],start=new Date(x.started_at),end=new Date(start.getTime()+MINING_HOURS*3600000),elapsed=Date.now()-start.getTime(),remaining=Math.max(0,MINING_HOURS*3600000-elapsed),earned=Number((Math.min(MINING_HOURS,Math.max(0,elapsed/3600000))*Number(x.rate_adt_per_hour)).toFixed(8));s.json({active:true,canClaim:elapsed>=MINING_HOURS*3600000,sessionId:x.id,startedAt:start.toISOString(),endsAt:end.toISOString(),rateADTPerHour:Number(x.rate_adt_per_hour),earnedADT:earned,maximumEarnedADT:DAILY_LIMIT,remainingSeconds:Math.ceil(remaining/1000)})}catch(e){authError(s,e)}});
app.post("/api/mining/stop",async(q,s)=>{if(!pool)return s.status(503).json({error:"Database is not configured."});const c=await pool.connect();try{const u=await requirePiUser(q);await c.query("BEGIN");const r=await c.query(`SELECT ms.id,ms.user_id,ms.started_at FROM mining_sessions ms JOIN users u ON u.id=ms.user_id WHERE u.pi_username=$1 AND ms.status='active' ORDER BY ms.started_at DESC LIMIT 1 FOR UPDATE`,[u.username]);if(!r.rows.length){await c.query("ROLLBACK");return s.status(404).json({error:"No active mining session."})}const x=r.rows[0],elapsed=Date.now()-new Date(x.started_at).getTime(),total=MINING_HOURS*3600000;if(elapsed<total){await c.query("ROLLBACK");return s.status(409).json({error:"Mining cycle is not complete yet.",remainingSeconds:Math.ceil((total-elapsed)/1000)})}await c.query(`UPDATE mining_sessions SET stopped_at=NOW(),status='completed',earned_adt=$1 WHERE id=$2`,[DAILY_LIMIT,x.id]);await c.query(`INSERT INTO balances(user_id,available_adt) VALUES($1,$2) ON CONFLICT(user_id) DO UPDATE SET available_adt=balances.available_adt+EXCLUDED.available_adt,updated_at=NOW()`,[x.user_id,DAILY_LIMIT]);await c.query(`UPDATE reputation_profiles SET completed_mining_cycles=completed_mining_cycles+1,updated_at=NOW() WHERE user_id=$1`,[x.user_id]);const b=await c.query(`SELECT available_adt FROM balances WHERE user_id=$1`,[x.user_id]);await c.query("COMMIT");s.json({message:"24-hour mining completed.",sessionId:x.id,earnedADT:DAILY_LIMIT,balanceADT:Number(b.rows[0].available_adt),reputation:await reputation(x.user_id)})}catch(e){try{await c.query("ROLLBACK")}catch{}authError(s,e)}finally{c.release()}});
app.get("/api/balance",async(q,s)=>{try{const u=await requirePiUser(q),r=await query(`SELECT u.pi_username,b.available_adt FROM users u JOIN balances b ON b.user_id=u.id WHERE u.pi_username=$1`,[u.username]);if(!r.rows.length)return s.status(404).json({error:"User not found."});s.json({piUsername:r.rows[0].pi_username,balanceADT:Number(r.rows[0].available_adt)})}catch(e){authError(s,e)}});
app.get("/api/reputation",async(q,s)=>{try{const u=await requirePiUser(q),user=await getUser(u.username);if(!user)return s.status(404).json({error:"User not found."});await profiles(user.id);await reputation(user.id);const r=await query(`SELECT score,level,completed_mining_cycles,wallet_verified,marketplace_purchases FROM reputation_profiles WHERE user_id=$1`,[user.id]);s.json({reputation:r.rows[0]})}catch(e){authError(s,e)}});
app.get("/api/mining/history",async(q,s)=>{try{const u=await requirePiUser(q),r=await query(`SELECT ms.id,ms.started_at,ms.stopped_at,ms.status,ms.rate_adt_per_hour,ms.earned_adt FROM mining_sessions ms JOIN users u ON u.id=ms.user_id WHERE u.pi_username=$1 ORDER BY ms.started_at DESC LIMIT 50`,[u.username]);s.json({history:r.rows})}catch(e){authError(s,e)}});
app.get("/api/marketplace/products",async(q,s)=>{try{const r=await query(`SELECT product_id,name,price,currency,visibility FROM marketplace_products WHERE active=TRUE AND visibility='public' ORDER BY id`);s.json({testnet:TESTNET_MODE,products:r.rows})}catch(e){s.status(500).json({error:"Unable to read marketplace products."})}});
app.post("/api/payments/approve",async(q,s)=>{try{const u=await requirePiUser(q),{paymentId}=q.body;if(typeof paymentId!=="string"||!paymentId)return s.status(400).json({error:"Invalid payment ID."});const payment=await piApiRequest(`/payments/${encodeURIComponent(paymentId)}/approve`,"POST",{});await query(`INSERT INTO payments(payment_id,pi_username,status) VALUES($1,$2,'approved') ON CONFLICT(payment_id) DO UPDATE SET pi_username=EXCLUDED.pi_username,status='approved'`,[paymentId,u.username]);s.json({ok:true,payment})}catch(e){authError(s,e)}});
app.post("/api/payments/complete",async(q,s)=>{if(!pool)return s.status(503).json({error:"Database is not configured."});const c=await pool.connect();try{const u=await requirePiUser(q),{paymentId,txid,product}=q.body;if(typeof paymentId!=="string"||typeof txid!=="string"||typeof product!=="string")return s.status(400).json({error:"Missing or invalid payment data."});if(product===TEST_PRODUCT_ID&&u.username!==DEVELOPER_USERNAME)return s.status(403).json({error:"This Testnet product is restricted to the developer account."});if(product===TEST_PRODUCT_ID&&!TESTNET_MODE)return s.status(403).json({error:"Developer test product is disabled outside Testnet mode."});const payment=await piApiRequest(`/payments/${encodeURIComponent(paymentId)}/complete`,"POST",{txid});const ur=await c.query(`SELECT id FROM users WHERE pi_username=$1`,[u.username]);if(!ur.rows.length)return s.status(404).json({error:"User not found."});await c.query("BEGIN");const amount=Number(payment.amount||0);const old=await c.query(`SELECT status FROM payments WHERE payment_id=$1 FOR UPDATE`,[paymentId]);if(old.rows.length&&old.rows[0].status==='completed'){await c.query("ROLLBACK");return s.json({ok:true,message:"Payment was already completed."})}await c.query(`INSERT INTO payments(payment_id,pi_username,product,amount,txid,status,completed_at) VALUES($1,$2,$3,$4,$5,'completed',NOW()) ON CONFLICT(payment_id) DO UPDATE SET pi_username=EXCLUDED.pi_username,product=EXCLUDED.product,amount=EXCLUDED.amount,txid=EXCLUDED.txid,status='completed',completed_at=NOW()`,[paymentId,u.username,product,amount,txid]);const p=await c.query(`INSERT INTO purchases(user_id,payment_id,product,amount,txid) VALUES($1,$2,$3,$4,$5) ON CONFLICT(payment_id) DO NOTHING RETURNING id`,[ur.rows[0].id,paymentId,product,amount,txid]);if(p.rows.length)await c.query(`UPDATE reputation_profiles SET marketplace_purchases=marketplace_purchases+1,updated_at=NOW() WHERE user_id=$1`,[ur.rows[0].id]);await c.query("COMMIT");s.json({ok:true,testnet:TESTNET_MODE,paymentId,txid,product,amount,reputation:await reputation(ur.rows[0].id)})}catch(e){try{await c.query("ROLLBACK")}catch{}authError(s,e)}finally{c.release()}});
app.get("/api/purchases",async(q,s)=>{try{const u=await requirePiUser(q),r=await query(`SELECT p.id,p.product,p.amount,p.txid,p.purchased_at FROM purchases p JOIN users u ON u.id=p.user_id WHERE u.pi_username=$1 ORDER BY p.purchased_at DESC`,[u.username]);s.json({purchases:r.rows})}catch(e){authError(s,e)}});
app.post("/api/wallet/register",async(q,s)=>{try{const u=await requirePiUser(q),{walletAddress}=q.body;if(typeof walletAddress!=="string")return s.status(400).json({error:"Wallet address is required."});const a=walletAddress.trim();if(a.length<20||a.length>150)return s.status(400).json({error:"Invalid wallet address format."});const user=await getUser(u.username);if(!user)return s.status(404).json({error:"User not found."});await profiles(user.id);const r=await query(`UPDATE wallet_profiles SET wallet_address=$1,verification_status='pending',verification_method=NULL,verified_at=NULL,updated_at=NOW() WHERE user_id=$2 RETURNING wallet_address,verification_status,verification_method,verified_at`,[a,user.id]);s.json({ok:true,wallet:r.rows[0]})}catch(e){authError(s,e)}});
app.get("/api/wallet/status",async(q,s)=>{try{const u=await requirePiUser(q),r=await query(`SELECT wp.wallet_address,wp.verification_status,wp.verification_method,wp.verified_at FROM wallet_profiles wp JOIN users u ON u.id=wp.user_id WHERE u.pi_username=$1`,[u.username]);if(!r.rows.length)return s.status(404).json({error:"Wallet profile not found."});s.json({wallet:r.rows[0]})}catch(e){authError(s,e)}});
async function startServer(){try{if(pool){await initializeDatabase();console.log("Database initialized.")}else console.log("DATABASE_URL is not configured yet.");if(!PI_API_KEY)console.warn("WARNING: PI_API_KEY is not configured.");console.log("ADT Environment:",TESTNET_MODE?"TESTNET":"MAINNET");app.listen(PORT,"0.0.0.0",()=>console.log(`ADT backend running on port ${PORT}`))}catch(e){console.error("Startup failed:",e);process.exit(1)}}
startServer();
